[package]
name = "lumina"
version = "0.1.0"
edition = "2021"
authors = ["Slamet Sugandi <packercyber@gmail.com>"]
description = "A beautiful, fast, and elegant web framework for Rust"
license = "MIT"

[lib]
name = "lumina"
path = "src/lib.rs"

[[bin]]
name = "lumina-server"
path = "src/main.rs"

[workspace]
members = ["lumina_macros"]

[dependencies]
lumina_macros = { path = "lumina_macros" }
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7", features = ["macros", "multipart"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0.15"
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
tracing-appender = "0.2"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "postgres", "mysql", "macros", "any", "chrono"] }
jsonwebtoken = "9"
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
tera = "1.19"
regex = "1"
validator = { version = "0.18", features = ["derive"] }
bcrypt = "0.15"
tower-http = { version = "0.5", features = ["catch-panic", "cors", "trace", "fs"] }
axum-extra = { version = "0.9", features = ["cookie", "cookie-private"] }
tower = "0.4"
thiserror = "2.0.18"
tower-sessions = "0.12"
tower-sessions-sqlx-store = { version = "0.13", features = ["mysql", "sqlite", "postgres"] }
time = "0.3.47"
axum_csrf = { version = "0.10.0", features = ["layer"] }
moka = { version = "0.12.15", features = ["future"] }
uuid = { version = "1", features = ["v4"] }
image = "0.25"
oauth2 = "4.4"
reqwest = { version = "0.12", features = ["json"] }
rand = "0.8"
fake = { version = "2.9", features = ["derive", "chrono"] }
rustyline = "14.0"
comfy-table = "7.1"
tokio-cron-scheduler = "0.10"


[[bin]]
name = "lumina"
path = "src/bin/lumina.rs"
