[package]
name = "lumina"
version = "0.1.0"
edition = "2021"
authors = ["Slamet Sugandi <packercyber@gmail.com>"]
description = "A beautiful, fast, and elegant web framework for Rust"
license = "MIT"

[lib]
name = "lumina"
path = "src/lib.rs"

[[bin]]
name = "lumina-server"
path = "src/main.rs"

[dependencies]
tokio = { version = "1", features = ["full"] }
axum = { version = "0.7", features = ["macros"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
dotenv = "0.15"
async-trait = "0.1"
tracing = "0.1"
tracing-subscriber = "0.3"
sqlx = { version = "0.8", features = ["runtime-tokio", "sqlite", "postgres", "mysql", "macros", "any"] }
jsonwebtoken = "9"
clap = { version = "4", features = ["derive"] }
chrono = "0.4"
tera = "1.19"
regex = "1"
validator = { version = "0.18", features = ["derive"] }
bcrypt = "0.15"
tower-http = { version = "0.5", features = ["catch-panic", "cors", "trace"] }
axum-extra = { version = "0.9", features = ["cookie", "cookie-private"] }
tower = "0.4"
thiserror = "2.0.18"
tower-sessions = "0.13"
tower-sessions-sqlx-store = { version = "0.13", features = ["sqlite"] }
time = "0.3.47"
axum_csrf = { version = "0.10.0", features = ["layer"] }

[[bin]]
name = "lumina"
path = "src/bin/lumina.rs"
