CREATE TABLE IF NOT EXISTS products (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    name       TEXT    NOT NULL,
    price      REAL    NOT NULL DEFAULT 0,
    deleted_at TIMESTAMP NULL DEFAULT NULL
);
